CREATE VIEW SALES_KPIz AS
SELECT

	(SELECT SUM(Subtotal_price) from SALEs) as TOTAL_REVENUE,

    (SELECT SUM(QUANTITY) FROM SALES) AS TOTAL_QUANTITY_SOLD,
    
    (SELECT COUNT(DISTINCT ORDER_NUMBER) FROM SALES) AS UNIQUE_ORDERS,
    
    (SELECT ROUND(AVG(SUBTOTAL_PRICE), 2) FROM SALES) AS AVERAGE_NET_ORDER_VALUE,
    
    (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM SALES) AS TOTAL_CUSTOMERS,
    
    (SELECT COUNT(*) 
     FROM (
         SELECT CUSTOMER_ID
         FROM SALES
         GROUP BY CUSTOMER_ID
         HAVING COUNT(ORDER_NUMBER) = 1
     ) AS one_time) AS ONE_TIME_CUSTOMERS,
    
    (SELECT ROUND(SUM(TOTAL_PRICE_USD)/COUNT(DISTINCT CUSTOMER_ID), 2)
     FROM SALES) AS AVERAGE_REVENUE_PER_CUSTOMER;

SELECT * FROM  sales_kpiz